# Example secrets for first-time GigHive setup.
# Change these before using in production.
# You can later encrypt this file with:
#   ansible-vault encrypt ansible/inventories/group_vars/prod/secrets.yml

mysql_root_password: "musiclibrary"
mysql_appuser_password: "musiclibrary"

# Use vault/encrypted vars in real life:
gighive_admin_password: "supersecretadmin"
gighive_viewer_password: "supersecretviewer"
gighive_uploader_password: "supersecretuploader"
