# Example secrets for first-time GigHive setup.
# Copy this file to secrets.yml and replace values with your own.
# For production or Internet-exposed deployments, always change these
# and consider using Ansible Vault or another secret manager.

mysql_root_password: "musiclibrary"
mysql_appuser_password: "musiclibrary"

# Use vault/encrypted vars in real life:
gighive_admin_password: "secretadmin"
gighive_viewer_password: "secretviewer"
gighive_uploader_password: "secretuploader"
