# Example secrets for first-time GigHive setup.
# Change these before using in production.
# You can later encrypt this file with:
#   ansible-vault encrypt ansible/inventories/group_vars/gighive_secrets.yml

mysql_root_password: "musiclibrary"
mysql_appuser_password: "musiclibrary"

# Use vault/encrypted vars in real life:
gighive_admin_password: "secretadmin"
gighive_viewer_password: "secretviewer"
gighive_uploader_password: "secretuploader"
