# Example secrets for first-time GigHive setup.
# Change these before using in production.
# You can later encrypt this file with:
#   ansible-vault encrypt ansible/inventories/group_vars/gighive_secrets.yml

mysql_root_password: "musiclibrary"
mysql_appuser_password: "musiclibrary"
