all:
  children:
    controller:
      hosts:
        baremetal:
          ansible_connection: local
          ansible_host: localhost
          ansible_python_interpreter: /usr/bin/python3

    target_vms:
      children:
        gighive: {}

    gighive:
      hosts:
        gighive_vm:
          ansible_host: 192.168.1.252
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          serve_one_shot_installer_downloads: true
          one_shot_bundle_source: url
