# One true repo root
repo_root: "{{ (playbook_dir | dirname | dirname) }}"

gighive_home: "{{ ansible_env.HOME }}/gighive"

# Convenience paths
roles_dir: "{{ repo_root }}/ansible/roles"
cloud_init_files_dir: "{{ roles_dir }}/cloud_init/files"

